- hosts: localhost
  gather_facts: false
  vars:
    myitems:
      - name: foo
        position: foo
      - name: bar
  tasks:
    - include: level1.yml
      args:
        myitem: "{{ item.name }}"
      when: item.position | default("normal") == "foo"
      with_items:
        "{{ myitems }}"
